// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenReportInBrowser(arg1) {
  return window['go']['main']['App']['OpenReportInBrowser'](arg1);
}

export function ScanProject(arg1) {
  return window['go']['main']['App']['ScanProject'](arg1);
}

export function SelectProject() {
  return window['go']['main']['App']['SelectProject']();
}
