// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenReportInBrowser(arg1:string):Promise<void>;

export function ScanProject(arg1:string):Promise<string>;

export function SelectProject():Promise<string>;
